theme: jekyll-theme-modernist

title: "Traffic Regulations Chatbot"
description: "A project overview and documentation for the Traffic Regulations Chatbot"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Roberto121c.github.io" # the base hostname & protocol for your site

# Options to configure the theme
show_downloads: true
show_releases: true

# Markdown processing options
markdown: kramdown
kramdown:
  input: GFM

# Repository settings
repository: Roberto121c/Traffic_Regulations_Chatbot
